(* Grammar of a type *)

type = function_type
     | array_type
     | dictionary_type
     | type_identifier
     | tuple_type
     | optional_type
     | implicitly_unwrapped_optional_type
     | protocol_composition_type
     | opaque_type
     | metatype_type
     | any_type
     | self_type
     | "(" type ")" ;
