(* Grammar of operators *)

operator = operator_head [ operator_characters ] ;
operator = dot_operator_head dot_operator_characters ;
operator_head = "/" | "=" | "-" | "+" | "!" | "*" | "%" | "<" | ">" | "&" | "|" | "^" | "~" | "?" ;
operator_head = /[\U000000A1-\U000000A7]/ ;
operator_head = /\U000000A9/ | /\U000000AB/ ;
operator_head = /\U000000AC/ | /\U000000AE/ ;
operator_head = /[\U000000B0-\U000000B1]/ ;
operator_head = /\U000000B6/ | /\U000000BB/ | /\U000000BF/ | /\U000000D7/ | /\U000000F7/ ;
operator_head = /[\U00002016-\U00002017]/ ;
operator_head = /[\U00002020-\U00002027]/ ;
operator_head = /[\U00002030-\U0000203E]/ ;
operator_head = /[\U00002041-\U00002053]/ ;
operator_head = /[\U00002055-\U0000205E]/ ;
operator_head = /[\U00002190-\U000023FF]/ ;
operator_head = /[\U00002500-\U00002775]/ ;
operator_head = /[\U00002794-\U00002BFF]/ ;
operator_head = /[\U00002E00-\U00002E7F]/ ;
operator_head = /[\U00003001-\U00003003]/ ;
operator_head = /[\U00003008-\U00003020]/ ;
operator_head = /\U00003030/ ;
operator_character = operator_head ;
operator_character = /[\U00000300-\U0000036F]/ ;
operator_character = /[\U00001DC0-\U00001DFF]/ ;
operator_character = /[\U000020D0-\U000020FF]/ ;
operator_character = /[\U0000FE00-\U0000FE0F]/ ;
operator_character = /[\U0000FE20-\U0000FE2F]/ ;
operator_character = /[\U000E0100-\U000E01EF]/ ;
operator_characters = operator_character [ operator_characters ] ;
dot_operator_head = "." ;
dot_operator_character = "." | operator_character ;
dot_operator_characters = dot_operator_character [ dot_operator_characters ] ;
infix_operator = operator ;
prefix_operator = operator ;
postfix_operator = operator ;
