(* Grammar of whitespace *)

whitespace = whitespace_item [ whitespace ] ;
whitespace_item = line_break
                | inline_space
                | comment
                | multiline_comment
                | /\U00000000/ | /\U0000000B/ | /\U0000000C/ ;
line_break = /\U0000000A/
           | /\U0000000D/
           | /\U0000000D/ /\U0000000A/ ;
inline_spaces = inline_space [ inline_spaces ] ;
inline_space = /\U00000009/ | /\U00000020/ ;
comment = "//" comment_text line_break ;
multiline_comment = "/*" multiline_comment_text "*/" ;
comment_text = comment_text_item [ comment_text ] ;
comment_text_item = unicode_scalar_value ~ ( /\U0000000A/ | /\U0000000D/ ) ;
multiline_comment_text = multiline_comment_text_item [ multiline_comment_text ] ;
multiline_comment_text_item = multiline_comment
                            | comment_text_item
                            | unicode_scalar_value ~ ( "/*" | "*/" ) ;
