(* Grammar of a pattern *)

pattern = wildcard_pattern [ type_annotation ]
        | identifier_pattern [ type_annotation ]
        | value_binding_pattern
        | tuple_pattern [ type_annotation ]
        | enum_case_pattern
        | optional_pattern
        | type_casting_pattern
        | expression_pattern ;
