(* Grammar of an availability condition *)

availability_condition = "#available" "(" availability_arguments ")"
                       | "#unavailable" "(" availability_arguments ")" ;
availability_arguments = availability_argument | availability_argument "," availability_arguments ;
availability_argument = platform_name platform_version
                      | "*" ;
platform_name = "iOS" | "iOSApplicationExtension"
              | "macOS" | "macOSApplicationExtension"
              | "macCatalyst" | "macCatalystApplicationExtension"
              | "watchOS" | "watchOSApplicationExtension"
              | "tvOS" | "tvOSApplicationExtension" ;
platform_version = decimal_digits
                 | decimal_digits "." decimal_digits
                 | decimal_digits "." decimal_digits "." decimal_digits ;
