(* Grammar of a compiler control statement *)

compiler_control_statement = conditional_compilation_block
                           | line_control_statement
                           | diagnostic_statement ;
