(* Grammar of a control transfer statement *)

control_transfer_statement = break_statement
                           | continue_statement
                           | fallthrough_statement
                           | return_statement
                           | throw_statement ;
