(* Grammar of a statement *)

statement = expression [ ";" ]
          | declaration [ ";" ]
          | loop_statement [ ";" ]
          | branch_statement [ ";" ]
          | labeled_statement [ ";" ]
          | control_transfer_statement [ ";" ]
          | defer_statement [ ";" ]
          | do_statement [ ";" ]
          | compiler_control_statement ;
statements = statement [ statements ] ;
