(* Grammar of a postfix expression *)

postfix_expression = primary_expression
                   | postfix_expression postfix_operator
                   | function_call_expression
                   | initializer_expression
                   | explicit_member_expression
                   | postfix_self_expression
                   | subscript_expression
                   | forced_value_expression
                   | optional_chaining_expression ;
