(* Grammar of a primary expression *)

primary_expression = identifier [ generic_argument_clause ]
                   | literal_expression
                   | self_expression
                   | superclass_expression
                   | closure_expression
                   | parenthesized_expression
                   | tuple_expression
                   | implicit_member_expression
                   | wildcard_expression
                   | key_path_expression
                   | selector_expression
                   | key_path_string_expression ;
