(* Grammar of a selector expression *)

selector_expression = "#selector" "(" expression ")"
                    | "#selector" "(" "getter:" expression ")"
                    | "#selector" "(" "setter:" expression ")" ;
