(* Grammar of a selector expression *)

selector_expression = "#selector" "(" expression ")" ;
selector_expression = "#selector" "(" "getter:" expression ")" ;
selector_expression = "#selector" "(" "setter:" expression ")" ;
