(* Grammar of an attribute *)

attribute = "@" attribute_name [ attribute_argument_clause ] ;
attribute_name = identifier ;
attribute_argument_clause = "(" [ balanced_tokens ] ")" ;
attributes = attribute [ attributes ] ;
balanced_tokens = balanced_token [ balanced_tokens ] ;
balanced_token = "(" [ balanced_tokens ] ")"
               | "[" [ balanced_tokens ] "]"
               | "{" [ balanced_tokens ] "}"
               | identifier | keyword | literal | operator
               | "!" | '"' | "#" | "$" | "%" | "&" | "'" | "*" | "+" | "," | "-" | "." | "/" | ":" | ";" | "<" | "=" | ">" | "?" | "@" | "\" | "^" | "_" | "`" | "|" | "~" ;
