(* ---------------- *)
(*   Declarations   *)
(* ---------------- *)

#include :: "declaration.ebnf"
#include :: "top-level-declaration.ebnf"
#include :: "code-block.ebnf"
#include :: "import-declaration.ebnf"
#include :: "constant-declaration.ebnf"
#include :: "variable-declaration.ebnf"
#include :: "type-alias-declaration.ebnf"
#include :: "function-declaration.ebnf"
#include :: "enumeration-declaration.ebnf"
#include :: "structure-declaration.ebnf"
#include :: "class-declaration.ebnf"
#include :: "actor-declaration.ebnf"
#include :: "protocol-declaration.ebnf"
#include :: "protocol-property-declaration.ebnf"
#include :: "protocol-method-declaration.ebnf"
#include :: "protocol-initializer-declaration.ebnf"
#include :: "protocol-subscript-declaration.ebnf"
#include :: "protocol-associated-type-declaration.ebnf"
#include :: "initializer-declaration.ebnf"
#include :: "deinitializer-declaration.ebnf"
#include :: "extension-declaration.ebnf"
#include :: "subscript-declaration.ebnf"
#include :: "operator-declaration.ebnf"
#include :: "precedence-group-declaration.ebnf"
#include :: "declaration-modifier.ebnf"
