(* Grammar of a declaration modifier *)

declaration_modifier = "class" | "convenience" | "dynamic" | "final" | "infix" | "lazy" | "optional" | "override" | "postfix" | "prefix" | "required" | "static" | "unowned" | "unowned" "(" "safe" ")" | "unowned" "(" "unsafe" ")" | "weak"
                     | access_level_modifier
                     | mutation_modifier
                     | actor_isolation_modifier ;
declaration_modifiers = declaration_modifier [ declaration_modifiers ] ;
access_level_modifier = "private" | "private" "(" "set" ")"
                      | "fileprivate" | "fileprivate" "(" "set" ")"
                      | "internal" | "internal" "(" "set" ")"
                      | "public" | "public" "(" "set" ")"
                      | "open" | "open" "(" "set" ")" ;
mutation_modifier = "mutating" | "nonmutating" ;
actor_isolation_modifier = "nonisolated" ;
