(* ------------------------------------ *)
(*   Generic Parameters and Arguments   *)
(* ------------------------------------ *)

#include :: "generic-parameter-clause.ebnf"
#include :: "generic-argument-clause.ebnf"
