(* Grammar of a generic argument clause *)

generic_argument_clause = "<" generic_argument_list ">" ;
generic_argument_list = generic_argument | generic_argument "," generic_argument_list ;
generic_argument = type ;
